=== AaronWilton/aaronwilton.github.io/_IPT Extension/extension-as-elements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 rel. 2 sp1 (x64) (http://www.altova.com) by Aaron Wilton (Landcare Research New Zealand Limit) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="extension">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title"/>
				<xs:element name="name"/>
				<xs:element name="namespace"/>
				<xs:element name="rowType"/>
				<xs:element name="creator" minOccurs="0"/>
				<xs:element name="issued" type="xs:date"/>
				<xs:element name="description" minOccurs="0"/>
				<xs:element name="relation" minOccurs="0"/>
				<xs:element name="subject" minOccurs="0"/>
				<xs:element name="property" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="namespace" type="xs:string"/>
							<xs:element name="qualName" type="xs:string"/>
							<xs:element name="group" type="xs:string" minOccurs="0"/>
							<xs:element name="columnLength" type="xs:int" minOccurs="0"/>
							<xs:element name="comments" minOccurs="0"/>
							<xs:element name="examples" minOccurs="0"/>
							<xs:element name="relation" minOccurs="0"/>
							<xs:element name="subject" minOccurs="0"/>
							<xs:element name="description" minOccurs="0"/>
							<xs:element name="thesaurus" minOccurs="0"/>
							<xs:element name="required" type="xs:boolean"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AaronWilton/aaronwilton.github.io/_IPT Extension/LocalContextProject-as-elements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This format is easier to edit that as attributes as the content doesn't wrap across the lines as much.
Use the transform-element-to-attribute.xslt to create the proper extension xml.-->
<extension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="extension-as-elements.xsd">
	<title>Local Context Project Demonstration</title>
	<name>LocalContextProject</name>
	<namespace>http://localcontext.org/api/terms/</namespace>
	<rowType>http://localcontext.org/api/terms/LocalContextProject</rowType>
	<creator>Aaron Wilton</creator>
	<issued>2025-09-19</issued>
	<description>This IPT extension **demonstrates** how Local Context Labels and Notices could be included in a structured way within resources. Once endorsed, this **may** provide an interim or transitional solution for the provision of Local Contexts information with occurrences while other standards work.
	
An extended veriant, like that for Measurements and Facts, could be created to allow linkage to occurrences for Sampling Event data.</description>
	<!--RECORD LEVEL-->
	<property>
		<name>RecordID</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextRecordID</qualName>
		<group>Record</group>
		<!--<examples>TO DO</examples>-->
		<!--<relation>TO DO</relation>-->
		<description>The identifier of the occurrence the measurement or fact refers to. If not applicable, it should be left empty.</description>
		<required>false</required>
	</property>
	<!--<property>
		<name>occurrenceID</name>
		<namespace>http://rs.tdwg.org/dwc/terms/</namespace>
		<qualName>http://rs.tdwg.org/dwc/terms/occurrenceID</qualName>
		<group>Record</group>
		--><!--<examples>TO DO</examples>--><!--
		<relation>http://rs.tdwg.org/dwc/terms/index.htm#occurrenceID</relation>
		<description>The identifier of the occurrence the measurement or fact refers to. If not applicable, it should be left empty.</description>
		<required>false</required>
	</property>-->	
	<property>
		<name>RecordDateAdded</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextDateAdded</qualName>
		<group>Record</group>
		<examples>2025-03-08T14:07-0600, 2021-02-20T08:40Z, 2023-02-12, 2026-06, 2022, 2022-03-01T13:00:00Z/2023-05-11T15:30:00Z, 2022-11-13/15</examples>
		<!--<relation>TO DO</relation>-->
		<description>The date on which the occurrence or event was added to the Project. Recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E).</description>
		<required>false</required>
	</property>
	<property>
		<name>RecordDateModified</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextDateModified</qualName>
		<group>Record</group>
		<examples>2025-03-08T14:07-0600, 2021-02-20T08:40Z, 2023-02-12</examples>
		<!--<relation>TO DO</relation>-->
		<description>The date on which the Local Context Project was last modified. Recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E).</description>
		<required>false</required>
	</property>
	<!--PROJECT-->
	<property>
		<name>localContextProjectID</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextProjectID</qualName>
		<group>Project</group>
		<!--<examples>TO DO</examples>
		<relation>TO DO</relation>-->
		<description>The unique identifier assigned to the project by Local Contexts.</description>
		<required>true</required>
	</property>
	<property>
		<name>localContextProjectTitle</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextProjectTitle</qualName>
		<group>Project</group>
		<comments>Optional.  This may be included when to ensure this information is available when the data set or records are used offline.</comments>
		<!--<examples>TO DO</examples>
		<relation>TO DO</relation>-->
		<description>The project title as recorded in the Local Contexts hub.</description>
		<required>false</required>
	</property>
	<property>
		<name>localContextProjectDateAdded</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextProjectDateAdded</qualName>
		<group>Project</group>
		<comments>Optional.  This may be included when to ensure this information is available when the data set or records are used offline.</comments>
		<examples>2025-03-08T14:07-0600, 2021-02-20T08:40Z, 2023-02-12, 2026-06, 2022, 2022-03-01T13:00:00Z/2023-05-11T15:30:00Z, 2022-11-13/15</examples>
		<!--<relation>TO DO</relation>-->
		<description>The date on which the Local Context Project was added. Recommended best practice is to use an encoding scheme, such as ISO 8601:2004(E).</description>
		<required>false</required>
	</property>
	
	<!--RELATIONS-->
	<property>
		<name>ProvidersProjectID</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/ProvidersProjectID</qualName>
		<group>Links</group>
		<comments>Optional.  This may be included when to ensure this information is available when the data set or records are used offline.</comments>
<!--		<examples>TO DO</examples>
		<relation>TO DO</relation>-->
		<description>A unique identifier for a project assigned by project creator. Included to assist cross-linking and searching.</description>
		<required>false</required>
	</property>
	<property>
		<name>localContextProjectPage</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextProjectPage</qualName>
		<group>Links</group>
		<comments>Optional.  This may be included when to provide a direct link to the Local Contexts Project for data users.</comments>
<!--		<examples>TO DO</examples>
		<relation>TO DO</relation>-->
		<description>The url to view the Local Context Project page.</description>
		<required>false</required>
	</property>
	<!--LABELS AND NOTICES-->
	<property>
		<name>localContextBCLabels</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextBCLabels</qualName>
		<group>Labels and Notices</group>
		<comments>Optional.  This may be included to support users when working offline, archiving of data sets, and to enable systems to display Label iconics without having to call the Local Contexts API.</comments>
		<examples>commercialization|research|multiple_community</examples>
		<relation>https://localcontexts.org/support/api-guide/v1/#variables</relation>
		<description>The type values for the Biocultural Labels that have been applied by the project.  This should be provided as a | delimited string.</description>
		<thesaurus>http://localcontext.org/api/vocabulary/BC_label_type.xml</thesaurus>
		<required>false</required>
	</property>
	<property>
		<name>localContextTKLabels</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextTKLabels</qualName>
		<group>Labels and Notices</group>
		<comments>Optional.  This may be included to support users when working offline, archiving of data sets, and to enable systems to display Label iconics without having to call the Local Contexts API.</comments>
		<examples>culturally_sensitive|seasonal</examples>
		<relation>https://localcontexts.org/support/api-guide/v1/#variables</relation>
		<description>The name of the Traditional Knowledge Labels that have been applied by the project.  This should be provided as a | delimited string.</description>
		<thesaurus>http://localcontext.org/api/vocabulary/TK_label_type.xml</thesaurus>
		<required>false</required>
	</property>
	<property>
		<name>localContextNotices</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextNotices</qualName>
		<group>Labels and Notices</group>
		<comments>Optional.  This may be included to support users when working offline, archiving of data sets, and to enable systems to display Label iconics without having to call the Local Contexts API.</comments>
		<examples>biocultural|open_to_collaborate</examples>
		<relation>https://localcontexts.org/support/api-guide/v1/#variables</relation>
		<description>The name of Notices that have been applied by the project.  This should be provided as a | delimited string.</description>
		<thesaurus>http://localcontext.org/api/vocabulary/notice_type.xml</thesaurus>
		<required>false</required>
	</property>
	<property>
		<name>localContextBCLabelsID</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextBCLabelsID</qualName>
		<group>Labels and Notices</group>
		<comments>Optional.  This may be included to support systems to retrieve Label information via the Local Context API.</comments>
		<!--<examples>TO DO</examples>
		<relation>TO DO</relation>-->
		<description>A list of the unique Local Context UUID assigned to each label listed in BClabels. This should be provided as a | delimited string.</description>
		<required>false</required>
	</property>
	<property>
		<name>localContextTKLabelsID</name>
		<namespace>http://localcontext.org/api/terms/</namespace>
		<qualName>http://localcontext.org/api/terms/localContextTKLabelsID</qualName>
		<group>Labels and Notices</group>
		<comments>Optional.  This may be included to support systems to retrieve Label information via the Local Context API.</comments>
		<!--<examples>TO DO</examples>
		<relation>TO DO</relation>-->
		<description>A list of the unique Local Context UUID assigned to each label listed in TKLabels. This should be provided as a | delimited string.</description>
		<required>false</required>
	</property>
	<property>
		<name>localContextNoticesID</name>
